from setuptools import setup, find_packages

setup(
    name="paralyzer",
    version="0.1.0",
    description="Resume & Profile Analyzer with Job Role Recommendations",
    author="Your Name",
    author_email="your.email@example.com",
    packages=find_packages(),
    install_requires=[
        "streamlit>=1.28.0",
        "pydantic>=2.0.0",
        "pyyaml>=6.0",
        "requests>=2.28.0",
        "python-dotenv>=1.0.0",
        "pandas>=1.5.0",
        "numpy>=1.24.0",
        "tiktoken>=0.5.0",
        "pydantic>=2.0.0",
        "python-magic>=0.4.0",
        "fake-useragent>=1.4.0",
        "beautifulsoup4>=4.12.0",
        "selenium>=4.15.0",
        "playwright>=1.40.0",
        "scrapy>=2.11.0",
        "lxml>=4.9.0",
        "cssselect>=1.2.0",
        "faker>=18.0.0",
        "pytz>=2023.0",
        "tzdata>=2023.0",
        "Pillow>=10.0.0",
        "openai>=1.0.0",
        "google-generativeai>=0.4.0",
        "anthropic>=0.21.0",
        "langchain>=0.1.0",
        "langchain-community>=0.0.10",
        "langchain-google-genai>=0.0.9",
        "weaviate-client>=4.0.0",
        "pypdf>=3.0.0",
        "docx2python>=2.1.0",
        "python-docx>=0.8.0",
        "PyPDF2>=3.0.0",
        "reportlab>=4.0.0",
        "plotly>=5.17.0",
        "plot>=0.5.0",
    ],
    python_requires=">=3.11",
    entry_points={
        "console_scripts": [
            "paralyzer=src.main:main",
        ],
    },
)